default: &default
  adapter: postgresql
  encoding: utf8
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: abcnews_development

test:
  <<: *default
  database: abcnews_test

production:
  <<: *default
  database: abcnews_production
